spring:
  h2:
    console:
      enabled: true
  jpa:
    #전송 쿼리 확인
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    #테이블 생성 후에 data.sql 실행 > 오류나서 import.sql 로 변경
    defer-datasource-initialization: true
  datasource:
    url: jdbc:h2:mem:testdb